In [1]:
import requests
import pandas as pd
from pprint import pprint

In [2]:
response = requests.get("https://dummyjson.com/recipes", {"limit":0})
response_json = response.json()

In [3]:
df = pd.DataFrame(response_json["recipes"])
df.head(2)

,id,name,ingredients,instructions,prepTimeMinutes,cookTimeMinutes,servings,difficulty,cuisine,caloriesPerServing,tags,userId,image,rating,reviewCount,mealType
0,1,Classic Margherita Pizza,"[Pizza dough, Tomato sauce, Fresh mozzarella c...","[Preheat the oven to 475°F (245°C)., Roll out ...",20,15,4,Easy,Italian,300,"[Pizza, Italian]",166,https://cdn.dummyjson.com/recipe-images/1.webp,4.6,98,[Dinner]
1,2,Vegetarian Stir-Fry,"[Tofu, cubed, Broccoli florets, Carrots, slice...","[In a wok, heat sesame oil over medium-high he...",15,20,3,Medium,Asian,250,"[Vegetarian, Stir-fry, Asian]",143,https://cdn.dummyjson.com/recipe-images/2.webp,4.7,26,[Lunch]

In [6]:
numeric_keys = df.describe().keys()
numeric_keys

Index(['id', 'prepTimeMinutes', 'cookTimeMinutes', 'servings',
       'caloriesPerServing', 'userId', 'rating', 'reviewCount'],
      dtype='object')

In [8]:
df = df.drop(numeric_keys,  axis=1)
df.head(2)

,name,ingredients,instructions,difficulty,cuisine,tags,image,mealType
0,Classic Margherita Pizza,"[Pizza dough, Tomato sauce, Fresh mozzarella c...","[Preheat the oven to 475°F (245°C)., Roll out ...",Easy,Italian,"[Pizza, Italian]",https://cdn.dummyjson.com/recipe-images/1.webp,[Dinner]
1,Vegetarian Stir-Fry,"[Tofu, cubed, Broccoli florets, Carrots, slice...","[In a wok, heat sesame oil over medium-high he...",Medium,Asian,"[Vegetarian, Stir-fry, Asian]",https://cdn.dummyjson.com/recipe-images/2.webp,[Lunch]

In [11]:
df["image"]

0      https://cdn.dummyjson.com/recipe-images/1.webp
1      https://cdn.dummyjson.com/recipe-images/2.webp
2      https://cdn.dummyjson.com/recipe-images/3.webp
3      https://cdn.dummyjson.com/recipe-images/4.webp
4      https://cdn.dummyjson.com/recipe-images/5.webp
5      https://cdn.dummyjson.com/recipe-images/6.webp
6      https://cdn.dummyjson.com/recipe-images/7.webp
7      https://cdn.dummyjson.com/recipe-images/8.webp
8      https://cdn.dummyjson.com/recipe-images/9.webp
9     https://cdn.dummyjson.com/recipe-images/10.webp
10    https://cdn.dummyjson.com/recipe-images/11.webp
11    https://cdn.dummyjson.com/recipe-images/12.webp
12    https://cdn.dummyjson.com/recipe-images/13.webp
13    https://cdn.dummyjson.com/recipe-images/14.webp
14    https://cdn.dummyjson.com/recipe-images/15.webp
15    https://cdn.dummyjson.com/recipe-images/16.webp
16    https://cdn.dummyjson.com/recipe-images/17.webp
17    https://cdn.dummyjson.com/recipe-images/18.webp
18    https://cdn.dummyjson.com/recipe-images/19.webp
19    https://cdn.dummyjson.com/recipe-images/20.webp
20    https://cdn.dummyjson.com/recipe-images/21.webp
21    https://cdn.dummyjson.com/recipe-images/22.webp
22    https://cdn.dummyjson.com/recipe-images/23.webp
23    https://cdn.dummyjson.com/recipe-images/24.webp
24    https://cdn.dummyjson.com/recipe-images/25.webp
25    https://cdn.dummyjson.com/recipe-images/26.webp
26    https://cdn.dummyjson.com/recipe-images/27.webp
27    https://cdn.dummyjson.com/recipe-images/28.webp
28    https://cdn.dummyjson.com/recipe-images/29.webp
29    https://cdn.dummyjson.com/recipe-images/30.webp
30    https://cdn.dummyjson.com/recipe-images/31.webp
31    https://cdn.dummyjson.com/recipe-images/32.webp
32    https://cdn.dummyjson.com/recipe-images/33.webp
33    https://cdn.dummyjson.com/recipe-images/34.webp
34    https://cdn.dummyjson.com/recipe-images/35.webp
35    https://cdn.dummyjson.com/recipe-images/36.webp
36    https://cdn.dummyjson.com/recipe-images/37.webp
37    https://cdn.dummyjson.com/recipe-images/38.webp
38    https://cdn.dummyjson.com/recipe-images/39.webp
39    https://cdn.dummyjson.com/recipe-images/40.webp
40    https://cdn.dummyjson.com/recipe-images/41.webp
41    https://cdn.dummyjson.com/recipe-images/42.webp
42    https://cdn.dummyjson.com/recipe-images/43.webp
43    https://cdn.dummyjson.com/recipe-images/44.webp
44    https://cdn.dummyjson.com/recipe-images/45.webp
45    https://cdn.dummyjson.com/recipe-images/46.webp
46    https://cdn.dummyjson.com/recipe-images/47.webp
47    https://cdn.dummyjson.com/recipe-images/48.webp
48    https://cdn.dummyjson.com/recipe-images/49.webp
49    https://cdn.dummyjson.com/recipe-images/50.webp
Name: image, dtype: object

In [14]:
df.image.count(), df.image.nunique()

(np.int64(50), 50)

In [15]:
df.name.count(), df.name.nunique()

(np.int64(50), 50)

In [16]:
df = df.drop("image", axis=1)
df.head(2)

,name,ingredients,instructions,difficulty,cuisine,tags,mealType
0,Classic Margherita Pizza,"[Pizza dough, Tomato sauce, Fresh mozzarella c...","[Preheat the oven to 475°F (245°C)., Roll out ...",Easy,Italian,"[Pizza, Italian]",[Dinner]
1,Vegetarian Stir-Fry,"[Tofu, cubed, Broccoli florets, Carrots, slice...","[In a wok, heat sesame oil over medium-high he...",Medium,Asian,"[Vegetarian, Stir-fry, Asian]",[Lunch]

In [17]:
print("difficulty", df.difficulty.nunique())
print("cuisine", df.cuisine.nunique())

difficulty 2
cuisine 21

In [18]:
df.difficulty.unique()

array(['Easy', 'Medium'], dtype=object)

In [20]:
df["new_difficulty"] = df["difficulty"] == "Easy"
df.head(2)

,name,ingredients,instructions,difficulty,cuisine,tags,mealType,new_difficulty
0,Classic Margherita Pizza,"[Pizza dough, Tomato sauce, Fresh mozzarella c...","[Preheat the oven to 475°F (245°C)., Roll out ...",Easy,Italian,"[Pizza, Italian]",[Dinner],True
1,Vegetarian Stir-Fry,"[Tofu, cubed, Broccoli florets, Carrots, slice...","[In a wok, heat sesame oil over medium-high he...",Medium,Asian,"[Vegetarian, Stir-fry, Asian]",[Lunch],False

In [21]:
df.describe()

,name,ingredients,instructions,difficulty,cuisine,tags,mealType,new_difficulty
count,50,50,50,50,50,50,50,50
unique,50,50,50,2,21,49,15,2
top,Classic Margherita Pizza,"[Pizza dough, Tomato sauce, Fresh mozzarella c...","[Preheat the oven to 475°F (245°C)., Roll out ...",Easy,Italian,"[Bruschetta, Italian]",[Dinner],True
freq,1,1,1,30,9,2,19,30

In [22]:
df.dtypes

name              object
ingredients       object
instructions      object
difficulty        object
cuisine           object
tags              object
mealType          object
new_difficulty      bool
dtype: object

In [25]:
df["new_difficulty"] = df["difficulty"].map({"Easy": 0, "Medium":1})
df.head(3)

,name,ingredients,instructions,difficulty,cuisine,tags,mealType,new_difficulty
0,Classic Margherita Pizza,"[Pizza dough, Tomato sauce, Fresh mozzarella c...","[Preheat the oven to 475°F (245°C)., Roll out ...",Easy,Italian,"[Pizza, Italian]",[Dinner],0
1,Vegetarian Stir-Fry,"[Tofu, cubed, Broccoli florets, Carrots, slice...","[In a wok, heat sesame oil over medium-high he...",Medium,Asian,"[Vegetarian, Stir-fry, Asian]",[Lunch],1
2,Chocolate Chip Cookies,"[All-purpose flour, Butter, softened, Brown su...","[Preheat the oven to 350°F (175°C)., In a bowl...",Easy,American,"[Cookies, Dessert, Baking]","[Snack, Dessert]",0

In [29]:
df["mealType"][2], type(df["mealType"][2])

(['Snack', 'Dessert'], list)

In [31]:
df["cuisine"].unique(), df["cuisine"].nunique()

(array(['Italian', 'Asian', 'American', 'Mexican', 'Mediterranean',
        'Pakistani', 'Japanese', 'Moroccan', 'Korean', 'Greek', 'Thai',
        'Indian', 'Turkish', 'Smoothie', 'Russian', 'Lebanese',
        'Brazilian', 'Spanish', 'Vietnamese', 'Cocktail', 'Hawaiian'],
       dtype=object),
 21)