In [16]:
import numpy as np
import pandas as pd

# 1. Încărcați DataFrame-ul de la ultimul execițiu

In [17]:
df = pd.read_csv("labeled_reviews.csv", index_col=0)
df

,review_uuid,review,review_length,sentiment
0,bd649b56-653e-47b6-82a4-22ed7d6631d3,very bad,2,negative
1,53c64956-156f-4ad1-9bb6-85f95d40c198,very good,2,positive
2,d56c2d26-296f-4e6e-b9f9-516d08f78cad,waste product dont buy,4,positive
3,7d2f7a42-a49e-474e-b2bd-4ca7159c4017,nice battery and fast charging,5,positive
4,1717eae1-06f1-45bc-826b-35eb2fd3cc5f,product works great large steel jar was little...,56,positive
...,...,...,...,...
2995,d2d936b5-5730-44b5-b0d8-81b811d427ed,very bad,2,negative
2996,154a6ac7-69a0-4d9a-9587-07dbf6113fb2,i have received the worst product from the sel...,29,negative
2997,ac610f15-7b2d-4610-b8cc-57643860c71e,quality of sole material is not good as well a...,13,positive
2998,75bd4a53-ff9a-47ff-abaa-8a17c71575de,after using 4 to 5 days ice cream is melting,10,positive
2999,499a943e-ac2d-46c9-a2c0-ab77e2425bf2,avg product cordlength is small and cooling sy...,15,positive

In [18]:
x = df["review"] # Serie
y = df["sentiment"] # Serie

In [19]:
x.shape, y.shape

((3000,), (3000,))

# 2. Vectorizează review-urile cu TfidfVectorizer.

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_vect = TfidfVectorizer()
tfidf_vect

TfidfVectorizer()

In [22]:
tfidf_vect.fit(x)

TfidfVectorizer()

In [23]:
x_tfidf = tfidf_vect.transform(x)
x_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 24826 stored elements and shape (3000, 3904)>

In [24]:
#x_tfidf = tfidf_vect.fit_transform(x)
#x_tfidf

In [25]:
x_tfidf.shape

(3000, 3904)

In [26]:
x_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(3000, 3904))

In [27]:
x_transformed = pd.DataFrame(x_tfidf.toarray(), columns=tfidf_vect.get_feature_names_out())
x_transformed

,08tb,10,100,1000,100mbps,1010,104mbps,10500h,10days,10k,...,youre,yourself,youtube,youuu,yr,yrs,zee5,zero,zerothey,zippers
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
x_transformed.shape

(3000, 3904)

# 3. Validează modelul prin metoda train/test

In [29]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_transformed, y, test_size=0.2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((2250, 3904), (750, 3904), (2250,), (750,))

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x_transformed, y, test_size=0.2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((2400, 3904), (600, 3904), (2400,), (600,))

In [33]:
type(x_train)

pandas.core.frame.DataFrame

In [34]:
x_train.iloc[0]

08tb        0.0
10          0.0
100         0.0
1000        0.0
100mbps     0.0
           ...
yrs         0.0
zee5        0.0
zero        0.0
zerothey    0.0
zippers     0.0
Name: 1178, Length: 3904, dtype: float64

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x_transformed, y, test_size=0.2, random_state=42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((2400, 3904), (600, 3904), (2400,), (600,))

In [36]:
from sklearn.naive_bayes import MultinomialNB

In [37]:
model = MultinomialNB()
model

MultinomialNB()

In [38]:
model.fit(x_train, y_train)

MultinomialNB()

In [41]:
y_predict = model.predict(x_test)
y_predict[:5]

array(['positive', 'positive', 'positive', 'negative', 'negative'],
      dtype='<U8')

In [43]:
prediction_df = pd.DataFrame({"Prezis":y_predict, "Real":y_test})
prediction_df

        Prezis      Real
1801  positive  positive
1190  positive  positive
1817  positive  positive
251   negative  negative
2505  negative  negative
...        ...       ...
104   positive  positive
2087  positive  positive
599   positive  positive
1756  positive  positive
1323  positive  positive

[600 rows x 2 columns]

In [44]:
(prediction_df.Prezis == prediction_df.Real).count()

np.int64(600)

In [45]:
my_review = input("Introdu un text ce urmeaza a fi un review")

In [46]:
my_review

'it was great'

In [50]:
my_review_transformed = tfidf_vect.transform([my_review])
my_review_transformed

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3 stored elements and shape (1, 3904)>

In [52]:
model.predict(my_review_transformed)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(

array(['positive'], dtype='<U8')